{% set name = "dotnet-interactive" %}
{% set version = "1.0.225602" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/interactive/archive/refs/tags/{{ version }}.tar.gz
  sha256: 234efeaff27f60038d81d3511abcc6fc9bbe1c69958e6c3ea35a6afca548dae7

build:
  skip: true  # [not win]
  number: 0

requirements:
  build:
    - dotnet >=5.0.100
  run:
    - {{ pin_compatible('dotnet', max_pin="x") }}

test:
  commands:
    - dotnet interactive --version

about:
  home: https://github.com/dotnet/interactive
  license: MIT
  license_file: License.txt
  summary: .NET Interactive takes the power of .NET and embeds it into your interactive experiences

extra:
  recipe-maintainers:
    - dhirschfeld
