{% set name = "dotnet-interactive" %}
{% set version = "1.0.4205010" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/interactive/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bf9e3301af0ef6e728e24bc613047af9b1ba123da4f6db25f132b7e58bae47f4
  # patches:
  #  - remove-assembly-info.patch

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - dotnet ~=7.0
    - nodejs ~=18.0
    - sysroot_linux-64 2.17  # [linux64]
  run:
    - {{ pin_compatible('dotnet', max_pin="x") }}

test:
  commands:
    - dotnet interactive --version
    - (! test -z $DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE)  # [unix]
    - if not defined DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE exit 1  # [win]

about:
  home: https://github.com/dotnet/interactive
  license: MIT
  license_file: License.txt
  summary: .NET Interactive takes the power of .NET and embeds it into your interactive experiences

extra:
  recipe-maintainers:
    - dhirschfeld
