if [[ -z "${_CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}" ]]; then
    export DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE="${_CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}"
else
    unset DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE
fi
