if [[ -z "${DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}" ]]; then
    export _CONDA_BACKUP_DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE="${DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE}"
fi

export DOTNET_INTERACTIVE_SKIP_FIRST_TIME_EXPERIENCE=true
